trigger:
  branches:
    include:
    - '*'
pr:
  branches:
    include:
    - '*'

jobs:
- job: Linux
  timeoutInMinutes: 360
  pool:
    vmImage: ubuntu-16.04

  steps:
  - template: linux-steps.yaml

- job: macOS
  timeoutInMinutes: 360
  pool:
    vmImage: macOS-10.14

  steps:
  - template: macos-steps.yaml
